### PR TITLE
Fix #727: add curl --fail

### LINKED ISSUE #727: curl --fail
Switch to this. Also for the boot scripts.

### PR DESCRIPTION
**Pull request by e-carlin**
Makes it easier to detect errors (e.g., bad GITHUB_TOKEN)

### CODE REVIEW

File: bin/index.sh [hunk 1]
```diff
@@ -20,7 +20,7 @@ index_main() {
             https://api.github.com/repos/radiasoft/download/contents/bin/install.sh
         )
     fi
-    curl --silent --show-error "${a[@]}" | bash ${install_debug:+-x} -s "$@"
+    curl --fail --silent --show-error "${a[@]}" | bash ${install_debug:+-x} -s "$@"
```
Comment (robnagler) [inline bin/index.sh:23]: `set -u` at the top, too.

**Review by robnagler — CHANGES_REQUESTED** [review]

**Review by robnagler — APPROVED** [review]
