### PR TITLE
Fix #412: geant4 installer

### LINKED ISSUE #412: geant4 installer
https://geant4-userdoc.web.cern.ch/UsersGuides/InstallationGuide/html/gettingstarted.html#softwarerequirements

Stephen C needs it but the work isn't associated with a RS project until March so there are no hours. He was trying `spack install geant4`  in the devbox but ran into https://stackoverflow.com/questions/50785575/configuring-qtbase-fails-with-an-error-could-not-find-qmake-spec . 

Since there are no hours I did the quickest thing I could think of - exec'd into his devbox as root, ran `dnf install qt5-qtbase-devel`, `su - vagrant`, `spack install geant4`. This worked. Leaving this as a placeholder to create a real installer once there are hours.

### PR DESCRIPTION
**Pull request by e-carlin**

### CODE REVIEW

File: installers/rpm-code/codes/geant4.sh [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+    'G4SAIDDATA.2.0'
+    'G4ABLA.3.1'
+    'G4INCL.1.0'
+    'G4ENSDFSTATE.2.3'
+    'G4TENDL.1.4'
+)
+
+for d in ${datasets[@]}; do
+    echo "Installing: $d"
+    curl -s -S -L https://cern.ch/geant4-data/datasets/"$d".tar.gz | tar xz --directory="$install_d"
```
Comment (robnagler) [inline installers/rpm-code/codes/geant4.sh:48]: `install_download https://cern.ch/geant4-data/datasets/"$d".tar.gz | ...`

File: installers/rpm-code/codes/geant4.sh [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+
+install_d=${1:-}
+if [[ ! $install_d ]]; then
+    echo "usage: $0 dataset-install-directory
+You must supply a directory where you want the datasets to be installed" 1>&2
+    exit 1
+fi
+
+declare datasets=(
+    'G4EMLOW.8.2'
```
Comment (robnagler) [inline installers/rpm-code/codes/geant4.sh:33]: (Single) quotes are unnecessary with literals unless they have specials or spaces, which usually they don't.

File: installers/rpm-code/codes/geant4.sh [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+)
+
+for d in ${datasets[@]}; do
+    echo "Installing: $d"
+    curl -s -S -L https://cern.ch/geant4-data/datasets/"$d".tar.gz | tar xz --directory="$install_d"
+done
+
+echo "
+You must set 'GEANT4_DATA_DIR=$install_d' when running geant4 for it to find the datsets
+For example: GEANT4_DATA_DIR=$install_d ./exampleB1"
```
Comment (robnagler) [inline installers/rpm-code/codes/geant4.sh:53]: Put this on its own line to make it easier to copy and paste:

```txt
For example: 
GEANT4_DATA_DIR=$install_d ./exampleB1"
```

I find multiline messages are easier to read with `cat <<EOF`, but this is a style thing.

File: installers/rpm-code/codes/geant4.sh [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+https://services.dartmouth.edu/TDClient/1806/Portal/KB/ArticleDet?ID=89669
+EOF
+
+geant4_install_data_download_script() {
+    install -m 555 /dev/stdin "${codes_dir[bin]}"/rs_geant4_download_data <<'EOF'
+#!/bin/bash
+set -eou pipefail
+
+install_d=${1:-}
+if [[ ! $install_d ]]; then
```
Comment (robnagler) [inline installers/rpm-code/codes/geant4.sh:26]: Check to see the directory exists and is writable, e.g. 

`if [[ $install_d && -d $install_d && -w $install_d ]]; then`

File: installers/rpm-code/codes/geant4.sh [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+On a Mac if the geant4 GUI appears but the space where the visualization should be is blank you may
+need to enable opengl:
+https://geant4-forum.web.cern.ch/t/qt-viewer-scene-tree-empty/1207/5 (which links to)
+https://services.dartmouth.edu/TDClient/1806/Portal/KB/ArticleDet?ID=89669
+EOF
+
+geant4_install_data_download_script() {
+    install -m 555 /dev/stdin "${codes_dir[bin]}"/rs_geant4_download_data <<'EOF'
+#!/bin/bash
+set -eou pipefail
```
Comment (robnagler) [inline installers/rpm-code/codes/geant4.sh:23]: Since this is a command that is installed somewhere, a header comment with usage and description is useful. One way to do this is:

```sh
#/bin/bash
#
# Install data sets for Geant4 from https://cern.ch/geant4-data/datasets
#
_USAGE="usage: $0 dataset-install-directory
You must supply a directory where you want the data sets to be installed"

**Review by robnagler — CHANGES_REQUESTED** [review]

File: installers/rpm-code/codes/geant4.sh (hunk 1 above)
Comment (e-carlin) [reply installers/rpm-code/codes/geant4.sh:48]: Should I download/source something to make install_* available? As the script currently sits install_download won't be available. I guess another option is to make it an "official" installer (radia_run ...) but I don't love splitting the code across multiple disconnected files.

File: installers/rpm-code/codes/geant4.sh [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+    'G4PII.1.3'
+    'G4RealSurface.2.2'
+    'G4SAIDDATA.2.0'
+    'G4ABLA.3.1'
+    'G4INCL.1.0'
+    'G4ENSDFSTATE.2.3'
+    'G4TENDL.1.4'
+)
+
+for d in ${datasets[@]}; do
```
[the remark this answers is not in the document]
Comment (e-carlin) [reply installers/rpm-code/codes/geant4.sh]: 1564945

File: installers/rpm-code/codes/geant4.sh (hunk 2 above)
Comment (e-carlin) [reply installers/rpm-code/codes/geant4.sh]: 1564945

File: installers/rpm-code/codes/geant4.sh (hunk 4 above)
Comment (e-carlin) [reply installers/rpm-code/codes/geant4.sh]: 1564945

File: installers/rpm-code/codes/geant4.sh (hunk 5 above)
Comment (e-carlin) [reply installers/rpm-code/codes/geant4.sh:26]: 1564945

File: installers/rpm-code/codes/geant4.sh (hunk 1 above)
Comment (robnagler) [reply installers/rpm-code/codes/geant4.sh:52]: Sorry, I was confused. Ignore.

**Review by robnagler — APPROVED** [review]
